<?php

namespace App\Utils;

class DBUtils
{
    /**
     * Parse sql file generated by DeZign for Databases for array of queries.
     *
     * @param string $fileName Sql filename to parse
     *
     * @return array|string[] Sql queries
     */
    public static function parseMultiSqlFile(string $fileName): array
    {
        $content = file_get_contents($fileName);
        // Replaced \n\n\n and explode by \n\n
        $queries = explode("\n\n", str_replace("\n\n\n", "\n\n", str_replace("\r\n", "\n", $content)));
        // Removed queries that starts like comments
        $queries = array_filter($queries, function ($line) {
            return $line[0] !== '#';
        });

        return $queries;
    }
}
